version: '3.8'

services:
  api:
    build: .
    container_name: monitorup-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database_psgrts:5432/${POSTGRES_DB}
    depends_on:
      - redis_cache
      - database_psgrts

  redis_cache:
    image: redis:alpine
    container_name: monitorup-redis
    ports:
      - "6379:6379"

  database_psgrts:
    image: postgres:15-alpine
    container_name: monitorup-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
